# Generated by Django 5.2 on 2026-09-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0030_plc_datapoint_mapping_p1'),
        ('teams', '0008_team_remote_control_epoch_team_remote_control_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsetupitem',
            name='candidate_key',
            field=models.CharField(blank=True, db_index=True, help_text='Stable identity used to retain an equipment draft across discovery scans.', max_length=320),
        ),
        migrations.AddField(
            model_name='deploymentsetupitem',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='deploymentsetupitem',
            constraint=models.UniqueConstraint(condition=models.Q(('candidate_key', ''), _negated=True), fields=('run', 'candidate_key'), name='unique_setup_candidate_key_per_run'),
        ),
    ]
